`openMRS` adding more functions
OpenFn/adaptors pull request #257
Opened 2023-05-24 19:14 UTC by mtuchi

## Implementation Plan
Add the following helper functions in `OpenMRS` adaptor
- [x]  searchPatient
- [x] searchPerson
- [x] createPatient
- [x] getPatient
- [x] getEncounter
- [x] getEncounters
- [x] createEncounter

## Issues

Reference any related issues here. #255 

## Review Checklist

Before merging, the reviewer should check the following items:

- [x] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, has the migration tool been run and the
      migration guide followed?
- [ ] Are there any unit tests? Should there be?
- [x] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.

2023-05-25 16:00 UTC, mtuchi commented
For testing `createEncounter()`
```
createEncounter({
  encounterDatetime: '2023-05-25T06:08:25.000+0000',
  patient: '1fdaa696-e759-4a7d-a066-f1ae557c151b',
  encounterType: 'dd528487-82a5-4082-9c72-ed246bd49591',
  location: 'ba685651-ed3b-4e63-9b35-78893060758a',
  encounterProviders: [],
  visit: {
    patient: '1fdaa696-e759-4a7d-a066-f1ae557c151b',
    visitType: '7b0f5697-27e3-40c4-8bae-f4049abfb4ed',
    startDatetime: '2023-05-25T06:08:25.000+0000',
    stopDatetime: '2023-05-25T06:09:25.000+0000',
  },
});
```

2023-05-29 09:09 UTC, stuartc requested changes
@mtuchi nice refactoring here, we need to address two things:

- Not wrapping `superagent` in promises since it already returns a promise.
- Making sure that those final catches aren't going to break when we throw custom errors.

2023-05-30 06:35 UTC, stuartc requested changes
@mtuchi I'm not stoked with these changes. How are we testing this?

I see the appeal to use `superagent` instead of `request`, but there seems to be a lot of changes that either seem to be unnecessary or ignore previous functionality.

Lets pair to get this sorted.

2023-05-30 06:35 UTC, stuartc commented on packages/openmrs/src/Adaptor.js
> +      });
I'm not sure what is going on here, it doesn't need to be wrapped in a promise; and you don't seem to be getting the response from the server?

2023-05-30 06:35 UTC, stuartc commented on packages/openmrs/src/Adaptor.js
> +          return nextState;
I see you're using `.end` here, and in other places. We need to pick one, either use the `.then` pattern or `.end`.

2023-05-30 06:35 UTC, stuartc commented on packages/openmrs/src/Adaptor.js
> +      });
You don't need to catch to throw an error. This is redundant.

2023-05-30 06:35 UTC, stuartc commented on packages/openmrs/src/Adaptor.js
> +      });
Please remove this.

2023-05-30 06:35 UTC, stuartc commented on packages/openmrs/src/Adaptor.js
> -            }
What happened to these logs/errors?

2023-05-30 13:47 UTC, merged