add googlehealthcare adaptor
OpenFn/adaptors pull request #288
Opened 2023-06-23 07:26 UTC by mtuchi

## Summary

Add a high-level, single-sentence summary of what this PR changes.

## Details

Add technical details of what you've changed (and why).

## Issues

Reference any related issues here.

## Review Checklist

Before merging, the reviewer should check the following items:

- [ ] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, has the migration tool been run and the
      migration guide followed?
- [ ] Are there any unit tests? Should there be?
- [ ] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.

2023-06-26 10:20 UTC, taylordowns2000 requested changes

2023-06-26 10:45 UTC, mtuchi commented on packages/googlehealthcare/assets/sq-256x256.png
I have updated the icons https://github.com/OpenFn/adaptors/pull/288/commits/ab7ac5a091bb87ee789d5603336d582140c0b997

2023-06-26 10:48 UTC, mtuchi commented on packages/googlehealthcare/CHANGELOG.md
Removed the typo

2023-06-27 07:44 UTC, taylordowns2000 approved these changes

2023-06-27 07:45 UTC, merged