new logos labled as rectangle.png or square.png
OpenFn/adaptors pull request #379
Opened 2023-09-04 06:48 UTC by aleksa-krolls

Following the specifications in the `template/assets` directory, @mrmatroxa has generated new app logos for all of the adaptors and labeled the files as `rectangle.png` or `square.png`. Please review and let him know if you have any feedback. 

Notes his comments in this spreadsheet re: a couple of questions and decisions taken. 
https://docs.google.com/spreadsheets/d/1zH7SAm9nfAGU7kHop0AGd0spOSRipPKHSdspL8_hx3E/edit#gid=0

2023-09-04 08:11 UTC, taylordowns2000 requested changes
looks great. thanks @MrMatroxa . please address the review comments and ensure that no artifacts of the previous naming convention are left behind. (you mentioned changes to msgraph... you should be deleting those other files in this PR. openfn? template? googlehealthcare? make sure that the whole _repo_ looks how you want it to look and re-request a review.

thank you!!!

2023-09-04 08:11 UTC, taylordowns2000 commented on packages/ocl/assets/rectangle.png
Is this definitely `Roboto`? Looks a little different from the website.
<img width="412" alt="image" src="https://github.com/OpenFn/adaptors/assets/8732845/7047e961-af87-41b5-889d-cf32a0aac0f6">

2023-09-04 08:11 UTC, taylordowns2000 commented on packages/common/assets/square.png
hrmmmmmm. this is not the square image from `template`. please use that. the alpha has been removed there so there's no transparency and that's important to keep the gradient right on off-white background.

2023-09-04 08:11 UTC, taylordowns2000 commented on packages/primero/assets/rectangle.png
we need a dark font-color version of this instead as we'll render on many light backgrounds

2023-09-04 08:11 UTC, taylordowns2000 commented on packages/twilio/assets/square.png
different color than the rectangular version. intentional?

2023-09-04 09:58 UTC, MrMatroxa commented on packages/primero/assets/rectangle.png
Do you want light AND dark text versions or just the dark one?

2023-09-04 10:13 UTC, MrMatroxa commented on packages/ocl/assets/rectangle.png
I took the font from the logo in the logo folder that I got from you. I can change it to Roboto.

2023-09-04 10:26 UTC, MrMatroxa commented on packages/twilio/assets/square.png
Will change to the same one

2023-09-05 20:44 UTC, aleksa-krolls commented on packages/ocl/assets/rectangle.png
@taylordowns2000 how are these? https://github.com/OpenFn/adaptors/tree/new-app-logs/packages/ocl/assets

2023-09-05 20:44 UTC, aleksa-krolls commented on packages/common/assets/square.png
copied over the one from the template

2023-09-05 20:44 UTC, aleksa-krolls commented on packages/primero/assets/rectangle.png
@taylordowns2000 we went with this one: https://github.com/OpenFn/adaptors/blob/new-app-logs/packages/primero/assets/rectangle.png

2023-09-05 20:45 UTC, aleksa-krolls commented on packages/twilio/assets/square.png
✅

2023-09-05 20:45 UTC, aleksa-krolls commented
@taylordowns2000 changes implemented, pls review and let me and @MrMatroxa know

2023-09-05 20:49 UTC, taylordowns2000 approved these changes

2023-09-05 20:49 UTC, merged