update scan to scan whole database
OpenFn/adaptors pull request #713
Opened 2024-08-08 08:03 UTC by mtuchi

## Summary

Add a high-level, single-sentence summary of what this PR changes.

## Details

Add technical details of what you've changed (and why).

## Issues

Reference any related issues here.

## Review Checklist

Before merging, the reviewer should check the following items:

- [ ] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, Added the adaptor on marketing website ?
- [ ] Are there any unit tests? Should there be?
- [ ] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.

2024-08-08 08:32 UTC, mtuchi commented
Hiya @josephjclark is first PR on redis improvements, I would love to hear your feedback on unit test if we need to add more

2024-08-08 08:56 UTC, josephjclark requested changes
looks great @mtuchi, let's add one more test and there's a couple of tiny suggestions

2024-08-08 10:08 UTC, mtuchi commented on packages/redis/src/Adaptor.js
> + * @property {string} type - Limits the keys returned to those of a specified type (e.g., string, list, set, hash, etc.).
Done

2024-08-08 10:09 UTC, mtuchi commented on packages/redis/test/Adaptor.test.js
> +  it('should return json keys', async () => {
I have added the test, but i don't how to assert the cursor state i each iteration

2024-08-09 09:17 UTC, mtuchi commented on packages/redis/test/Adaptor.test.js
> +  it('should return json keys', async () => {
Let me try this

2024-08-09 09:23 UTC, mtuchi commented
Hiya @josephjclark i have created a `release/redis` branch. Should i change the base for this branch and update the changeset in `release/redis` branch ?

2024-08-09 10:07 UTC, josephjclark commented on packages/redis/test/Adaptor.test.js
> +  it('should return json keys', async () => {
Great!

2024-08-09 10:07 UTC, josephjclark approved these changes

2024-08-09 10:07 UTC, merged