Update `salesforce` jsdocs
OpenFn/adaptors pull request #799
Opened 2024-10-25 10:46 UTC by mtuchi

## Summary

Update params docs and improve examples in salesforce adaptor  

Fixes #664 

## Details

Add technical details of what you've changed (and why).

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [x] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Review Checklist

Before merging, the reviewer should check the following items:

- [x] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, added the adaptor on marketing website ?
- [ ] Are there any unit tests?
- [ ] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.
- [x] Have you ticked a box under AI Usage?

2024-10-30 13:53 UTC, josephjclark commented
@mtuchi Please make angry noises at me if this isn't done tomorrow morning

2024-10-30 15:58 UTC, josephjclark commented
@mtuchi is this targeted at main? I expected this to be part of the next salesforce stuff, branching from `epic/salesforce`

2024-10-30 16:14 UTC, josephjclark requested changes
Yeah @mtuchi unfortunately these docs are against the wrong branch. You have examples of state.references, but we're about to remove that stuff.

This needs to be be retargeted and mapped to the epic

I've left a couple of high level comments which will need to be taken into account

2024-10-30 16:14 UTC, josephjclark commented on packages/salesforce/src/Adaptor.js
> + * bulkQuery('SELECT Id, Name FROM Patient__c');
These examples don't use any dynamic state. We should make sure there's at least one example which uses state (or lazy state)

2024-10-30 16:14 UTC, josephjclark commented on packages/salesforce/src/Adaptor.js
> + *   console.log(state.references[0]); // Log the retrieved record
Is the comment here useful? `console.log()` is  a pretty easy to understand function

2024-10-30 16:14 UTC, josephjclark commented on packages/salesforce/src/Adaptor.js
> + * @example <caption>Create a new record if `state.isNew` is true</caption>
Let's not add new examples for deprecated APIs please

2024-11-01 16:49 UTC, mtuchi commented
Sorry @josephjclark i wasn't able to work on change request this week, I will pick this up next week. I only manage to resolved git conflicts on #691

2024-11-12 18:38 UTC, closed without merging

2024-11-12 18:38 UTC, mtuchi commented
Closing this in favor of https://github.com/OpenFn/adaptors/pull/821